stages:
  - quality-assurance
  - testing
  - deploy

# Cache pip
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

linters:
  image: python:3.9
  stage: quality-assurance
  before_script:
    - pip install tox
  script:
    - tox -e linters

  # Be nice to new contributors, but please use `tox` before commit
  allow_failure: true

tests-debian-10:
  image: debian:10
  stage: testing
  before_script:
    - apt-get update && apt-get install -y tox python3-gi python3-gi-cairo python3-websockets gir1.2-gst-plugins-bad-1.0 gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-nice
  script:
    - tox -e tests

tests-archlinux:
  image: archlinux:latest
  stage: testing
  before_script:
    - pacman -Sy --noconfirm python-setuptools python-tox python-websockets python-gobject gobject-introspection gst-python gst-plugins-base gst-plugins-bad
  script:
    - tox -e tests

deploy:
  image: python:3.9
  stage: deploy
  before_script:
    - pip install build twine
  script:
    - python -m build
    - TWINE_PASSWORD=${PIPY_TOKEN} TWINE_USERNAME=__token__ python -m twine upload --repository pypi dist/*
  only:
    refs:
      - tags
